- name: update cache
    apt: 
      update_cache: yes 
      cache_valid_time: 3600 


- sysctl:  
    name: kernel.shmmax
    value: 
    state: present 

- sysctl: 
    name: kernel.shmmall 
    value: 
    state: present 

- sysctl: 
    name: vm.swappiness
    value: 
    state: present 



- name: Install Postgresql  
  command: apt install postgresql postgresql-contrib libpq-dev python-psycopg2
  when: ansible_os_family = "Debian" or ansible_os_family = "Ubuntu" 
